version: '3.8'
services:
  mongodb:
    image: mongo:7.0-alpine
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: jarvis

  jarvis:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    volumes:
      - ./audio_files:/app/audio_files

volumes:
  mongodb_data:
